version: '3.7'

services:
    client:
        build: .
        image: java:latest
        networks:
            - javanet
networks:
    javanet:
        name: javanet
        ipam:
            driver: default
            config:
                - subnet: "172.20.255.0/24"

